controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
emplacement_show:
    path: \emplacement\{id}
    controller: App\Controller\EmplacementController::show

app_payment:
  path: /payment
  controller: App\Controller\PaymentController::index
  methods: GET

checkout:
  path: /checkout
  controller: App\Controller\PaymentController::checkout
  methods: POST

success_url:
  path: /success-url
  controller: App\Controller\PaymentController::successUrl
  methods: GET

cancel_url:
  path: /cancel-url
  controller: App\Controller\PaymentController::cancelUrl
  methods: GET

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

email:
  path: /email
  controller: App\Controller\MailerController::sendEmail

forgotpass:
  path: /forgotpass
  controller: App\Controller\RegistrationController::forgotpass

forgotpassemail:
  path: /forgotpassemail
  controller: App\Controller\RegistrationController::forgotpassemail

app_logout_success:
  path: /logout/success
  # Add any controller or use it as a placeholder since your LogoutListener will handle the logic

home:
  path: /home
  controller: App\Controller\HomeController::home



user_update:
  path: /user/update
  controller: App\Controller\RegistrationController::updateUser
  methods: ['GET', 'POST']


user_profile:
  path: /user/update
  controller: App\Controller\RegistrationController::updateUser



app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

api_login_check:
  path: /api/login_check

