# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    photo_dir: "%kernel.project_dir%/public/images"
    proof_directory: '%kernel.project_dir%/public/uploads/proofs'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    stripe_secret_key: 'sk_test_51PAapwLWTWqzZXJ4R91lV1zjd19S9uyY4gRloD8c1kwmoAS3XdveJTFPXBJUbgH7TCSrw3DUG4XWMwZl5jmM446s00y2QEuJTe'
services:
    Knp\Bundle\PaginatorBundle\PaginatorBundle:
        public: true
    App\EventSubscriber\CalendarSubscriber:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Service\OpenWeatherMapService:
        arguments:
            $apiKey: '%openweathermap_api_key%'
    App\Service\WeatherService:
        arguments:
            $apiKey: '%openweathermap_api_key%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
